2024-09-05 17:45:19,926: ERROR	pgadmin:	Database migration failed
2024-09-05 17:45:19,929: ERROR	pgadmin:	Traceback (most recent call last):
  File "/Library/PostgreSQL/17/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/alembic/operations/batch.py", line 690, in drop_constraint
    const = self.named_constraints.pop(const.name)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'ck_port_range'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/PostgreSQL/17/pgAdmin 4.app/Contents/Resources/web/pgadmin/__init__.py", line 386, in upgrade_db
    db_upgrade(app)
  File "/Library/PostgreSQL/17/pgAdmin 4.app/Contents/Resources/web/pgadmin/setup/db_upgrade.py", line 25, in db_upgrade
    flask_migrate.upgrade(migration_folder)
  File "/Library/PostgreSQL/17/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/flask_migrate/__init__.py", line 111, in wrapped
    f(*args, **kwargs)
  File "/Library/PostgreSQL/17/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/flask_migrate/__init__.py", line 200, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/Library/PostgreSQL/17/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/alembic/command.py", line 406, in upgrade
    script.run_env()
  File "/Library/PostgreSQL/17/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/alembic/script/base.py", line 582, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/Library/PostgreSQL/17/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/alembic/util/pyfiles.py", line 95, in load_python_file
    module = load_module_py(module_id, path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/PostgreSQL/17/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/alembic/util/pyfiles.py", line 113, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Library/PostgreSQL/17/pgAdmin 4.app/Contents/Resources/web/pgadmin/setup/../../migrations/env.py", line 95, in <module>
    run_migrations_online()
  File "/Library/PostgreSQL/17/pgAdmin 4.app/Contents/Resources/web/pgadmin/setup/../../migrations/env.py", line 87, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/Library/PostgreSQL/17/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/alembic/runtime/environment.py", line 946, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/Library/PostgreSQL/17/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/alembic/runtime/migration.py", line 628, in run_migrations
    step.migration_fn(**kw)
  File "/Library/PostgreSQL/17/pgAdmin 4.app/Contents/Resources/web/migrations/versions/7c56ea250085_.py", line 26, in upgrade
    with op.batch_alter_table("server") as batch_op:
  File "/Library/PostgreSQL/17/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 144, in __exit__
    next(self.gen)
  File "/Library/PostgreSQL/17/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/alembic/operations/base.py", line 398, in batch_alter_table
    impl.flush()
  File "/Library/PostgreSQL/17/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/alembic/operations/batch.py", line 162, in flush
    fn(*arg, **kw)
  File "/Library/PostgreSQL/17/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/alembic/operations/batch.py", line 701, in drop_constraint
    raise ValueError("No such constraint: '%s'" % const.name)
ValueError: No such constraint: 'ck_port_range'

2024-09-05 17:45:19,929: ERROR	pgadmin:	Exception in database migration.
2024-09-05 17:45:25,909: WARNING	werkzeug:	Werkzeug appears to be used in a production deployment. Consider switching to a production web server instead.
2024-09-05 17:46:30,051: WARNING	werkzeug:	Werkzeug appears to be used in a production deployment. Consider switching to a production web server instead.
2024-09-05 17:46:30,052: ERROR	pgadmin:	Error starting the app server: (<class 'BrokenPipeError'>, BrokenPipeError(32, 'Broken pipe'), <traceback object at 0x117512440>)
2024-09-05 17:50:54,756: WARNING	werkzeug:	Werkzeug appears to be used in a production deployment. Consider switching to a production web server instead.
2024-09-05 17:50:54,757: ERROR	pgadmin:	Error starting the app server: (<class 'BrokenPipeError'>, BrokenPipeError(32, 'Broken pipe'), <traceback object at 0x115075b40>)
2024-09-05 20:31:46,932: WARNING	werkzeug:	Werkzeug appears to be used in a production deployment. Consider switching to a production web server instead.
2024-09-05 20:31:46,934: ERROR	pgadmin:	Error starting the app server: (<class 'BrokenPipeError'>, BrokenPipeError(32, 'Broken pipe'), <traceback object at 0x1169597c0>)
